### ISSUE TITLE
Code for Downloading PDF is commented out

### ISSUE THREAD

**Issue by 1UnboundedSentience** [kumarrk21/PDFViewer#2]
The code for the buttons in the PDF viewer for Downloading PDF is commented out, thus I am unable to download a PDF with this viewer unless I uncomment the code:

1. Go to 'lcins1_pdfjs/web/viewer.html'

2. Code for the download button is commented out, you'd have to uncomment it and reupload it as a static resource:

                <button id="download" class="toolbarButton download hiddenMediumView" title="Download" tabindex="34" data-l10n-id="download">
                  <span data-l10n-id="download_label">Download</span>
                </button>

**Comment by kumarrk21** [comment]
Yes, that was on purpose as I built this for mobile and download button doesn't make sense for mobile. You are welcome to uncomment the code after your import it to your org.
