### ISSUE TITLE
var pdfjsLib = window['pdfjs-dist/build/pdf'] in aura component

### ISSUE THREAD

**Issue by richa-1369** [kumarrk21/PDFViewer#5]
Hi ,

Using var pdfjsLib = window['pdfjs-dist/build/pdf'] in aura component results in 'undefined' . 
What is the way to parsea pdf file if we have a link of a pdf file , instead of PDF data in base64 encoded format.

Thanks .

**Comment by kumarrk21** [comment]
Sorry, that is beyond the scope of this component. There are other resources available to help you get the PDF data in b64 format from a link.
