### ISSUE TITLE
Unable to Access Download and Print Functionality

### ISSUE THREAD

**Issue by nkannath** [kumarrk21/PDFViewer#6]
It appears that the static resource provided has commented out the download and print functionality (showing the icons that allow printing or downloading of the pdf). The resource file itself is not able to be modified, could you point me in the right direction or release a full version of PDFViewer with download and print?

**Comment by kumarrk21** [comment]
You should be able to download the resources from your instance, remove the commented out sections and upload the new version of the resource - https://help.salesforce.com/articleView?id=sf.pages_static_resources_edit.htm&type=5. IIRC I had disabled print from mobile app as it wasn't working properly. For desktop app, it should work.
